#!/bin/bash

platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
   platform='freebsd'
elif [[ "$unamestr" == 'Darwin' ]]; then
   platform='osx'
fi

if [ "$platform" = "osx" ]; then
  open $1
elif [ "$platform" = "linux" ]; then
  google-chrome $1 2>&1 > /dev/null &
else
  echo $url
fi
