#!/bin/bash
MYREPO=$2
UPSTREAM=$1

usage() {
   echo "Usage:"
   echo "$0 <upstream-remote> <target-remote>"
   echo ""
   echo "Example which ensures remote named 'origin' has everything from 'forked-from'"
   echo "$0 forked-from origin"
   exit 1
}

if [ -z "$UPSTREAM" ]
then
 echo Missing forked-from remote name.
 usage
fi

if [ -z "$MYREPO" ]
then
 echo Missing target remote name. 
 usage
fi

read -p "This will setup '$MYREPO' to track all branches in '$UPSTREAM' - Are you sure ?"

if [[ $REPLY =~ ^[Yy]$ ]]
then
 git fetch "$UPSTREAM"
 for brname in `git branch -r | grep "$UPSTREAM" | grep -v master | grep -v HEAD | sed -e 's/.*\///g'`; do git branch --track $brname  $UPSTREAM/$brname ; done
fi

read -p "This will push all local branches and tags into '$MYREPO' - Are you sure ?"

if [[ $REPLY =~ ^[Yy]$ ]]
then
 git push --all $MYREPO
 git push --tags $MYREPO
fi
