#!/bin/bash
if [ "$#" -eq 1 ] ; then
  remote=$1
else
  remote="$(git remote | grep upstream)"
  if [ "$remote" = "" ]; then
    remote="origin"
  fi
fi
echo "Fetching data from $remote"
git fetch $remote
for candidate in `git branch | sed 's/\*/ /' | grep -E ' candidate-| master$| stable$' | sed 's/\*//'`
do
  git merge-ff -q $candidate $remote/$candidate
done
